server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /wazuh/ {
        try_files $uri $uri/ /wazuh/index.html;
    }

    location = / {
        return 301 /wazuh/;
    }

    location = /healthz {
        access_log off;
        return 200 "ok";
        add_header Content-Type text/plain;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
}
