import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import {
  Box, Button, CircularProgress, Skeleton, Stack, TextField, Typography,
} from '@mui/material'
import { useTheme } from '@mui/material/styles'
import DownloadRoundedIcon from '@mui/icons-material/DownloadRounded'
import AssessmentRoundedIcon from '@mui/icons-material/AssessmentRounded'
import { soarApi, IrisCase, CaseTask, CaseEvidence, CaseActivityEntry, ShuffleAction, extractCaseIocs } from '../../../services/soarApi'
import { fmtIrisTimeToBangkok, fmtTime } from '../soarUtils'

interface Props {
  caseId: number
  caseData: IrisCase | null
}

function buildMarkdown(
  caseData: IrisCase | null,
  tasks: CaseTask[],
  iocs: unknown[],
  timeline: unknown[],
  evidence: CaseEvidence[],
  activity: CaseActivityEntry[],
  shuffleActions: ShuffleAction[],
  lessons: string,
  recommendations: string,
): string {
  const now = new Date().toLocaleString('th-TH')
  const doneTasks = tasks.filter(t => t.status === 'done')
  const pendingTasks = tasks.filter(t => t.status !== 'done')

  const lines: string[] = [
    `# Incident Report — ${caseData?.case_name ?? 'Case #' + caseData?.case_id}`,
    ``,
    `**สร้างเมื่อ:** ${now}  `,
    `**Case ID:** ${caseData?.case_id}  `,
    `**สถานะ:** ${caseData?.case_close_date ? 'ปิดแล้ว' : 'เปิดอยู่'}  `,
    `**เปิดโดย:** ${caseData?.opened_by ?? '—'}  `,
    `**ผู้รับผิดชอบ:** ${caseData?.owner ?? '—'}  `,
    `**วันที่เปิด:** ${caseData?.case_open_date ?? '—'}  `,
    caseData?.case_close_date ? `**วันที่ปิด:** ${caseData.case_close_date}  ` : '',
    ``,
    `---`,
    ``,
    `## รายละเอียดเคส`,
    ``,
    caseData?.case_description ? caseData.case_description : '_ไม่มีรายละเอียด_',
    ``,
    `---`,
    ``,
    `## Tasks (${tasks.length} รายการ)`,
    ``,
    `**เสร็จสิ้น:** ${doneTasks.length}/${tasks.length}`,
    ``,
    ...tasks.map(t => `- [${t.status === 'done' ? 'x' : ' '}] **[${t.priority.toUpperCase()}]** ${t.title}${t.assignee ? ` _(${t.assignee})_` : ''}`),
    ``,
    `---`,
    ``,
    `## Indicators of Compromise (IOC) — ${(iocs as Record<string, unknown>[]).length} รายการ`,
    ``,
    ...(iocs as Record<string, unknown>[]).map(ioc => `- \`${ioc.ioc_value}\` (${(ioc.ioc_type as Record<string, unknown>)?.type_name ?? 'unknown'})`),
    iocs.length === 0 ? '_ไม่มี IOC_' : '',
    ``,
    `---`,
    ``,
    `## Timeline (${(timeline as Record<string, unknown>[]).length} เหตุการณ์)`,
    ``,
    ...(timeline as Record<string, unknown>[]).slice(0, 20).map(ev => `- **${fmtIrisTimeToBangkok((ev.event_date_wtz as string) || (ev.event_date as string), (ev.event_tz as string) || '+00:00')}** — ${ev.event_title}`),
    timeline.length === 0 ? '_ไม่มีเหตุการณ์_' : '',
    ``,
    `---`,
    ``,
    `## Evidence (${evidence.length} รายการ)`,
    ``,
    ...evidence.map(ev => [
      `- **${ev.title}** [${ev.source}/${ev.ev_type}]`,
      ev.source_ref ? `  Source Ref: \`${ev.source_ref}\`` : '',
      ev.ioc_value ? `  IOC: \`${ev.ioc_value}\`${ev.ioc_type ? ` (${ev.ioc_type})` : ''}` : '',
      ev.sha256 ? `  SHA256: \`${ev.sha256}\`` : '',
    ].filter(Boolean).join('\n')),
    evidence.length === 0 ? '_ไม่มี evidence_' : '',
    ``,
    `---`,
    ``,
    `## Shuffle Actions (${shuffleActions.length} รายการ)`,
    ``,
    ...shuffleActions.map(a => `- **${a.action_type}** [${a.response_mode}] ${a.response_ok ? '✓' : '✗'} — ${fmtTime(a.created_at)}`),
    shuffleActions.length === 0 ? '_ไม่มี action_' : '',
    ``,
    `---`,
    ``,
    `## Activity Log (ล่าสุด ${Math.min(activity.length, 10)} รายการ)`,
    ``,
    ...activity.slice(0, 10).map(a => `- **${a.action}** — ${a.detail ?? ''} _(${a.username ?? '?'}, ${fmtTime(a.created_at)})_`),
    ``,
    `---`,
    ``,
    `## Recommendations`,
    ``,
    recommendations || '_ยังไม่ได้กรอก_',
    ``,
    `---`,
    ``,
    `## Lessons Learned`,
    ``,
    lessons || '_ยังไม่ได้กรอก_',
    ``,
    `---`,
    ``,
    `_Report generated by SOC Center — ${now}_`,
  ]

  return lines.filter(l => l !== '').join('\n')
}

export default function ReportPanel({ caseId, caseData }: Props) {
  const { palette } = useTheme()
  const isDark = palette.mode === 'dark'
  const textMuted = isDark ? 'rgba(255,255,255,0.3)' : 'rgba(60,40,100,0.45)'
  const cardBg    = isDark ? 'rgba(255,255,255,0.02)' : 'rgba(248,246,255,0.8)'

  const [lessons, setLessons] = useState('')
  const [recommendations, setRecommendations] = useState('')
  const [generating, setGenerating] = useState(false)
  const [preview, setPreview] = useState('')

  const { data: tasksData }   = useQuery({ queryKey: ['case-tasks', caseId],    queryFn: () => soarApi.getCaseTasks(caseId).then(r => r.data),    enabled: !!caseId })
  const { data: iocsData }    = useQuery({ queryKey: ['case-iocs', caseId],     queryFn: () => soarApi.getCaseIocs(caseId).then(r => r.data),     enabled: !!caseId })
  const { data: timelineData }= useQuery({ queryKey: ['case-timeline', caseId], queryFn: () => soarApi.getCaseTimeline(caseId).then(r => r.data), enabled: !!caseId })
  const { data: evData }      = useQuery({ queryKey: ['case-evidence', caseId], queryFn: () => soarApi.getCaseEvidence(caseId).then(r => r.data), enabled: !!caseId })
  const { data: actData }     = useQuery({ queryKey: ['case-activity', caseId], queryFn: () => soarApi.getCaseActivity(caseId).then(r => r.data), enabled: !!caseId })
  const { data: shaData }     = useQuery({ queryKey: ['shuffle-actions', caseId], queryFn: () => soarApi.getShuffleActions(caseId).then(r => r.data), enabled: !!caseId })

  const handleGenerate = () => {
    setGenerating(true)
    const md = buildMarkdown(
      caseData,
      tasksData?.tasks ?? [],
      extractCaseIocs(iocsData),
      timelineData?.data?.timeline ?? [],
      evData?.evidence ?? [],
      actData?.activity ?? [],
      shaData?.actions ?? [],
      lessons,
      recommendations,
    )
    setPreview(md)
    setGenerating(false)
  }

  const handleDownloadMd = () => {
    if (!preview) return
    const blob = new Blob([preview], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `incident_report_case${caseId}_${Date.now()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleDownloadJson = () => {
    const payload = {
      case: caseData,
      tasks: tasksData?.tasks ?? [],
      iocs: extractCaseIocs(iocsData),
      timeline: timelineData?.data?.timeline ?? [],
      evidence: evData?.evidence ?? [],
      activity: actData?.activity ?? [],
      shuffle_actions: shaData?.actions ?? [],
      lessons_learned: lessons,
      recommendations,
      generated_at: new Date().toISOString(),
    }
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `incident_report_case${caseId}_${Date.now()}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <Stack spacing={3}>
      {/* Recommendations + Lessons */}
      <Box className="rounded-xl p-3.5" sx={{ background: cardBg, border: `1px solid ${isDark ? 'rgba(255,255,255,0.07)' : 'rgba(99,102,241,0.1)'}` }}>
        <Typography className="text-[9px] font-bold tracking-widest mb-3" sx={{ color: textMuted }}>
          ข้อมูลสำหรับ REPORT
        </Typography>
        <Stack spacing={2}>
          <TextField
            size="small" multiline rows={3} label="Recommendations (คำแนะนำ)"
            value={recommendations} onChange={e => setRecommendations(e.target.value)} fullWidth
            placeholder="ข้อแนะนำเพื่อป้องกันเหตุการณ์ซ้ำ..."
            sx={{ '& .MuiOutlinedInput-root': { borderRadius: '10px', fontSize: 12 } }}
          />
          <TextField
            size="small" multiline rows={3} label="Lessons Learned (บทเรียนที่ได้รับ)"
            value={lessons} onChange={e => setLessons(e.target.value)} fullWidth
            placeholder="บทเรียนที่ได้รับจากเหตุการณ์นี้..."
            sx={{ '& .MuiOutlinedInput-root': { borderRadius: '10px', fontSize: 12 } }}
          />
        </Stack>
      </Box>

      {/* Action buttons */}
      <Box className="flex flex-wrap gap-2">
        <Button variant="contained" startIcon={generating ? <CircularProgress size={14} color="inherit" /> : <AssessmentRoundedIcon />}
          onClick={handleGenerate} disabled={generating}
          sx={{ borderRadius: 2, fontSize: 12, fontWeight: 700, background: '#6366F1', '&:hover': { background: '#4F46E5' } }}>
          สร้าง Report
        </Button>
        {preview && (
          <>
            <Button variant="outlined" startIcon={<DownloadRoundedIcon />} onClick={handleDownloadMd}
              sx={{ borderRadius: 2, fontSize: 12, borderColor: 'rgba(99,102,241,0.4)', color: '#6366F1', '&:hover': { borderColor: '#6366F1', background: 'rgba(99,102,241,0.06)' } }}>
              Download Markdown
            </Button>
            <Button variant="outlined" startIcon={<DownloadRoundedIcon />} onClick={handleDownloadJson}
              sx={{ borderRadius: 2, fontSize: 12, borderColor: 'rgba(56,189,248,0.4)', color: '#38BDF8', '&:hover': { borderColor: '#38BDF8', background: 'rgba(56,189,248,0.06)' } }}>
              Download JSON
            </Button>
          </>
        )}
      </Box>

      {/* Markdown preview */}
      {preview && (
        <Box className="rounded-xl overflow-hidden"
          sx={{ border: `1px solid ${isDark ? 'rgba(255,255,255,0.08)' : 'rgba(99,102,241,0.15)'}` }}>
          <Box className="px-3 py-2 flex items-center justify-between"
            sx={{ background: isDark ? 'rgba(255,255,255,0.04)' : 'rgba(99,102,241,0.05)', borderBottom: `1px solid ${isDark ? 'rgba(255,255,255,0.07)' : 'rgba(99,102,241,0.1)'}` }}>
            <Typography sx={{ fontSize: 10, fontWeight: 700, color: '#6366F1', letterSpacing: '0.06em' }}>MARKDOWN PREVIEW</Typography>
          </Box>
          <Box className="overflow-auto max-h-96 p-3"
            sx={{ background: isDark ? 'rgba(0,0,0,0.2)' : 'rgba(248,246,255,0.8)' }}>
            <pre style={{
              margin: 0, fontSize: 11,
              color: isDark ? 'rgba(255,255,255,0.75)' : '#1A1033',
              fontFamily: '"IBM Plex Mono", monospace',
              whiteSpace: 'pre-wrap', wordBreak: 'break-word', lineHeight: 1.7,
            }}>
              {preview}
            </pre>
          </Box>
        </Box>
      )}
    </Stack>
  )
}
